Repository grafana/dskit, pull requests merged in 2021-08, with the labels that each got.

#3 Move backoff from util/backoff to dskit/backoff. Rename backoff config to config for clarity
  backoff/backoff.go
  backoff/backoff_test.go
Labels: chore

#9 Add services package
  go.mod
  go.sum
  services/README.md
  services/basic_service.go
  services/basic_service_test.go
  services/example_test.go
  services/failure_watch_test.go
  services/failure_watcher.go
  services/manager.go
  services/manager_test.go
  services/service.go
  services/services.go
  services/services_test.go
Labels: enhancement

#10 Fix linting issues after enabling CI
  services/basic_service.go
  services/failure_watch_test.go
Labels: chore

#16 Add flagext package
  flagext/cidr.go
  flagext/cidr_test.go
  flagext/day.go
  flagext/day_test.go
  flagext/deprecated.go
  flagext/ignored.go
  flagext/register.go
  flagext/secret.go
  flagext/secret_test.go
  flagext/stringslice.go
  flagext/stringslicecsv.go
  flagext/stringslicecsv_test.go
  flagext/time.go
  flagext/time_test.go
  flagext/url.go
  flagext/url_test.go
  go.mod
Labels: enhancement

#14 Add kv package
  go.mod
  go.sum
  kv/client.go
  kv/client_test.go
  kv/codec/codec.go
  kv/consul/client.go
  kv/consul/client_test.go
  kv/consul/metrics.go
  kv/consul/mock.go
  kv/etcd/etcd.go
  kv/etcd/mock.go
  kv/kv_test.go
  kv/kvtls/test/ca.go
  kv/kvtls/test/tls_integration_test.go
  kv/kvtls/tls.go
  kv/kvtls/tls_test.go
  kv/memberlist/broadcast.go
  kv/memberlist/broadcast_test.go
  kv/memberlist/kv.pb.go
  kv/memberlist/kv.proto
  kv/memberlist/kv_init_service.go
  kv/memberlist/kv_init_service_test.go
  kv/memberlist/memberlist_client.go
  kv/memberlist/memberlist_client_test.go
  kv/memberlist/memberlist_logger.go
  kv/memberlist/mergeable.go
  kv/memberlist/metrics.go
  kv/memberlist/tcp_transport.go
  kv/metrics.go
  kv/mock.go
  kv/multi.go
  kv/multi_test.go
  kv/prefix.go
Labels: enhancement

#20 kv/consul: Close mock
  closer/closer.go
  kv/client.go
  kv/consul/client_test.go
  kv/consul/mock.go
  kv/etcd/mock.go
  kv/kv_test.go
Labels: bug

#19 Clean up golang ci lint issues for services and kv package
  kv/memberlist/kv_init_service.go
  kv/memberlist/memberlist_client.go
  services/basic_service.go
  services/failure_watcher.go
  services/manager.go
  services/service.go
  services/services.go
Labels: chore

#21 Remove dependency on Thanos
  go.mod
  go.sum
  kv/kvtls/test/ca.go
  kv/memberlist/dnsprovider.go
  kv/memberlist/kv_init_service.go
  kv/memberlist/kv_init_service_test.go
  kv/memberlist/memberlist_client.go
  kv/memberlist/memberlist_client_test.go
  multierror/multierror.go
  runutil/capture.go
Labels: chore
