Repository grafana/dskit, pull requests merged in 2023-06, with the labels that each got.

#310 kv: Make the Client.CAS doc comment more complete
  kv/client.go
Labels: documentation

#311 Upgrade to golangci-lint v1.53.2 and faillint v1.11.0
  .drone/drone.jsonnet
  .drone/drone.yml
  Makefile
  dns/miekgdns/resolver.go
  dns/resolver_test.go
  grpcclient/grpcclient.go
  kv/client_test.go
  kv/consul/client.go
  kv/consul/client_test.go
  kv/consul/mock.go
  kv/memberlist/memberlist_client.go
  kv/memberlist/memberlist_client_test.go
  kv/mock.go
  kv/multi_test.go
  limiter/rate_limiter_test.go
  loser/loser.go
  ring/basic_lifecycler_delegates.go
  ring/bench/ring_memberlist_test.go
  ring/client/pool.go
  ring/client/pool_test.go
  ring/flush.go
  ring/lifecycler_test.go
  ring/ring.go
  ring/ring_test.go
  ring/util_test.go
  runutil/runutil_test.go
  services/basic_service_test.go
  services/manager.go
  services/manager_test.go
Labels: chore

#79 ring.Lifecycler: Handle when previous ring state is leaving and the number of tokens has changed
  CHANGELOG.md
  ring/lifecycler.go
  ring/lifecycler_test.go
Labels: bug

#317 Include token 0 in ring.CountTokens()
  ring/ring.go
  ring/ring_test.go
  ring/util.go
  ring/util_test.go
Labels: bug

#321 Introducing SpreadMinimizingTokenGenerator
  ring/ownership_priority_queue.go
  ring/ownership_priority_queue_test.go
  ring/ring.go
  ring/spread_minimizing_token_generator.go
  ring/spread_minimizing_token_generator_test.go
  ring/token_generator.go
  ring/util.go
  ring/util_test.go
Labels: enhancement

#325 Make ring.CountTokens() take into account instances zones
  CHANGELOG.md
  ring/ring.go
  ring/ring_test.go
Labels: bug

#329 Add a basic help target to the Makefile
  Makefile
Labels: documentation

#328 Add docs for the ring package
  ring/basic_lifecycler.go
  ring/doc.go
  ring/lifecycler.go
  ring/ring.go
  ring/ring.pb.go
  ring/ring.proto
Labels: documentation
