Repository grafana/dskit, pull requests merged in 2023-08, with the labels that each got.

#350 [Chore] Updated minimum required Go version to 1.19 to ensure compatibility with OpenTelemetry version 1.14.0
  .drone/drone.jsonnet
  .drone/drone.yml
  CHANGELOG.md
  go.mod
  httpgrpc/server/server.go
Labels: chore

#356 Migrate weaveworks/common packages used by Loki
  CHANGELOG.md
  aws/config.go
  aws/config_test.go
  go.mod
  go.sum
  test/diff.go
Labels: enhancement

#355 fix: timer leak in backoff
  backoff/backoff.go
Labels: enhancement

#358 Test against Go 1.21 on CI
  .drone/drone.jsonnet
  .drone/drone.yml
  crypto/tls/test/tls_integration_go_1_20_test.go
  crypto/tls/test/tls_integration_go_1_21_test.go
  crypto/tls/test/tls_integration_test.go
Labels: chore

#360 Upgrade to github.com/hashicorp/golang-lru v2
  cache/lru.go
  cache/lru_test.go
  go.mod
  go.sum
Labels: chore

#363 server: Better document new server.TLSConfig parameters
  CHANGELOG.md
  server/server.go
  server/server_test.go
Labels: documentation, enhancement
