Repository grafana/dskit, pull requests merged in 2024-08, with the labels that each got.

#552 crypto/tls.ClientConfig: Set Config.Certificates for backwards compat
  CHANGELOG.md
  crypto/tls/tls.go
  crypto/tls/tls_test.go
Labels: bug

#553 Add read only ingester support to lifecycler and ring
  CHANGELOG.md
  ring/basic_lifecycler.go
  ring/basic_lifecycler_delegates_test.go
  ring/basic_lifecycler_test.go
  ring/bench/ring_memberlist_test.go
  ring/lifecycler.go
  ring/lifecycler_test.go
  ring/model.go
  ring/model_test.go
  ring/partition_instance_ring_test.go
  ring/ring.pb.go
  ring/ring.proto
  ring/ring_http.go
  ring/ring_status.gohtml
  ring/ring_test.go
  ring/spread_minimizing_token_generator_test.go
  servicediscovery/ring_test.go
Labels: enhancement, component/ring

#554 Add read only support for computing shuffle shards
  CHANGELOG.md
  ring/ring.go
  ring/ring_test.go
Labels: enhancement, component/ring

#570 Upgrade to golangci-lint v1.60.1
  Makefile
  grpcutil/status_test.go
  httpgrpc/httpgrpc.go
  httpgrpc/httpgrpc_test.go
  middleware/grpc_instrumentation_test.go
  ring/replication_set.go
  server/server_test.go
Labels: chore

#579 Remove Drone config
  .drone/drone.jsonnet
  .drone/drone.yml
  Makefile
  contributing/how-to-upgrade-golang-version.md
Labels: chore
